name: Check Markdown links

on:
  push:
    branches:
    - main
  schedule:
  # every sunday at 03:00 
  - cron: "0 3 * * 0"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        base-branch: 'main'
        use-verbose-mode: 'yes'
