name: Check Markdown links

on:
  push:
    branches:
    - master
  schedule:
  # every sunday at 03:00 
  - cron: "0 3 * * 0"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
